# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: AuthService
server:
  port: 8083
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
user:
  service:
    url: http://localhost:8761/USERSERVICE
logging:
  level:
    org:
      springframework:
        web: DEBUG
jwt:
secret: M2pRb3lTSU1qNlFyQ0hkV3Brc0h0NmtFb3FoV3R5ZmM=
expiration-ms: 86400000

